version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports: ["2181:2181"]
    networks: [app-net]

  kafka:
    image: wurstmeister/kafka:latest
    ports: ["9092:9092"]
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "legit_transactions:1:1"
    depends_on: [zookeeper]
    networks: [app-net]

  postgres:
    image: postgres:13
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taxi_db
    networks: [app-net]

  jobmanager:
    image: apache/flink:1.16.1-scala_2.12
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    ports: ["8081:8081"]
    networks: [app-net]

  taskmanager:
    image: apache/flink:1.16.1-scala_2.12
    depends_on: [jobmanager]
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks: [app-net]

  taxi-stream-app:
    build:
      context: .
      dockerfile: Dockerfile.flink-app
    depends_on: [jobmanager, taskmanager, kafka, postgres]
    networks: [app-net]

networks:
  app-net:
    driver: bridge
